### ISSUE TITLE
Making BadRow sealed trait

### ISSUE THREAD

**Issue by aldemirenes** [snowplow-incubator/snowplow-badrows#17]
In Loaders, we are creating bad rows with payload and failure directly and they are pairs like [this one](https://github.com/snowplow-incubator/snowplow-bigquery-loader/blob/release/0.2.0/loader/src/main/scala/com/snowplowanalytics/snowplow/storage/bigquery/loader/BadRow.scala#L84). So, we are guaranteeing payload and failure correspondence, i.e. it cannot be collector payload + loader failure.

However, in here, there is a [generic bad row class](https://github.com/snowplow-incubator/snowplow-badrows/blob/release/0.1.0/src/main/scala/com.snowplowanalytics.snowplow.badrows/BadRow.scala), we can not guarantee correct failure and payload will be used. Even though, they are specified in the schemas, someone can use different payload-failure pair then corresponding schema. So, we can create property based tests whether they are correct for expected pairs however we can not guarantee their usages will match the schema all the time. I think it would be better to make `BadRow` a sealed trait and specify payload-failure pairs explicitly like in the BQ Loader. What do you think about it @benjben ?

**Comment by benjben** [comment]
I think that it makes a lot of sense. Too bad that the design of the new bad rows was not a joint effort between the collectors, enrich jobs and loaders.

If `BadRow` becomes a trait we'll still be able to use `json.as[BadRow]` right?

**Comment by aldemirenes** [comment]
Sure, it can be used like that.

**Comment by benjben** [comment]
This issue includes:
[x] Adding BQ loader bad rows
[x] Adding Scaladoc to describe the different types of bad rows
[x] Splitting tracker protocol violations and adapter failures
