### ISSUE TITLE
Remove PartiallyEnrichedEvent from EnrichmentPayload

### ISSUE THREAD

**Issue by benjben** [snowplow-incubator/snowplow-badrows#19]

**Comment by chuwy** [comment]
Pushing this back to 0.2.0. I also don't see a reason to have `PartiallyEnrichedEvent` because technically enrichments always should produce the same output for same `RawEvent`. Even if we for some reasons need it - it should be Scala Analytics SDK `Event`, not ad-hoc untyped class.

**Comment by chuwy** [comment]
Actually, why this needs to be pushed back? @peel, @dilyand, @benjben do we use it anywhere in consumer apps? If not - we can delete it in 0.1.0.

**Comment by dilyand** [comment]
It is used in `gcp-bad-rows-aggregator` to extract `app_id` and `v_tracker`: 
- https://github.com/snowplow-product/gcp-bad-rows-aggregator/blob/schema-violations/src/main/scala/com/snowplowanalytics/monitoring/googlecloud/badrows/aggregates/BadRowExtract.scala#L91-L92
- https://github.com/snowplow-product/gcp-bad-rows-aggregator/blob/schema-violations/src/main/scala/com/snowplowanalytics/monitoring/googlecloud/badrows/aggregates/BadRowExtract.scala#L202-L203

**Comment by chuwy** [comment]
Ok, let's not change it then. But generally, some info like this should be available on `RawEvent`

**Comment by benjben** [comment]
Indeed all the information that we need should be in `RawEvent`.

**Comment by chuwy** [comment]
There's a case @peel discovered for `EnrichedEvent`. Basically all predicates and "fix functions" of a recovery job should work with `EnrichedEvent` and never with `RawEvent` because with `RawEvent` it would mean we need to decode URL parameters, which is considerably harder.

**Comment by benjben** [comment]
Could you give an example of when we need `PartiallyEnrichedEvent` ?

**Comment by dilyand** [comment]
When you want to filter by a field that is not available in the raw event, but might be available in the partially enriched event if it failed at a stage that comes after populating the field.

**Comment by benjben** [comment]
Got it! Thanks @dilyand
