### ISSUE TITLE
Consider adding refined types

### ISSUE THREAD

**Issue by chuwy** [snowplow-incubator/snowplow-badrows#22]
```scala
case class Foo(message: FiniteString[W.`256`.T])

object Foo {
  def apply(message: String): Foo =
    Foo(FiniteString[W.`256`.T].truncate(message))
}
```

This will truncate data in producers, but also make sure that data is 100% valid against schemas.

**Comment by dilyand** [comment]
How will we then catch schema validation errors, where a string exceeds the max length for example?

**Comment by chuwy** [comment]
We have two options:

1. There are functions to validate the string, so we would get `Either[Error, Foo]`. It means we would need to have bad bad rows.
2. We don't validate them and just truncate

Both options are bad, but third option is having something potentially invalid.
