### ISSUE TITLE
Consider adding invalid collector request

### ISSUE THREAD

**Issue by chuwy** [snowplow-incubator/snowplow-badrows#24]
Currently, we have only `SizeViolation` produced by collector. But Stream Collector also can [reject a request](https://github.com/snowplow/snowplow/pull/4011/files#diff-4d9d5134bd9a8a3df816fec651847ad4L282-L437) because of lack of `u` parameter. Pre-R118 returned 400 HTTP and produced a bad row. Now it seems we just send back 400 HTTP and do not produce a bad row.

What approach should be preferred? I think just 400 HTTP makes sense because it makes clear enough to tracking side that event was not collected. Also I don't think there's a lot of value in these type of bad rows - I never seen recovery requests for it.

/cc @dilyand @benjben

**Comment by benjben** [comment]
The only advantage that I see in having this bad row would be to have metrics about it. But this we could achieve with observability, so indeed creating a bad row does not make much sense.

If we create a bad row, couldn't it be a [CPFormatViolation](https://github.com/snowplow-incubator/snowplow-badrows/blob/release/0.1.0/src/main/scala/com.snowplowanalytics.snowplow.badrows/BadRow.scala#L91) ?

**Comment by dilyand** [comment]
I think it's valuable to be able to tell users that it failed precisely for lack of `u` parameter. If that can be done with a `CPFormatViolation` without compromising ease of debugging, then I'm all for it.

**Comment by dilyand** [comment]
But, to argue the opposite point as well, we ended up with many bad row types because they *are* all different things. So maybe conflating them now is not a good idea.
