### ISSUE TITLE
Update enrichment failures so that it can contain a list of Iglu errors

### ISSUE THREAD

**Issue by benjben** [snowplow-incubator/snowplow-badrows#30]
When at least one of the contexts added by the enrich job is invalid, an enrichment failure is emitted wrapping an `IgluError`.

At the moment such a bad row can contain the information about only one invalid context, whereas there can be several at the same time.  

`FailureDetails.EnrichmentFailure` should evolve so that it can contain a `List[IgluError]`.

**Comment by chuwy** [comment]
Or rather `NonEmptyList[IgluError]` maybe?

**Comment by benjben** [comment]
It's already the case, I got confused.
